### PR TITLE
Feat/minor bugs

### PR DESCRIPTION
**Pull request by cardosofede**

### CODE REVIEW

**Comment by nikspz** [comment]
Steps:

1. Clone backend-apiPR18 and dashboardPR153
2. Manually build docker image with docker build -t hummingbot/backend-api:latest -f Dockerfile . and docker build -t hummingbot/dashboard:latest -f Dockerfile .
3. clone https://github.com/hummingbot/deploy
4. for setup.sh removed line "docker compose pull"
5. bash setup.sh
6. go to http://localhost:8501/Portfolio

Actual: 
Review the issue reported before still ongoing

image

Tried on another chrome account, same thing

image


Steps:
1. go to portfolio
2. Create account with only whitespace

Actual:
Created successfully

image

image

**Comment by nikspz** [comment]
There's AttributeError: 'NoneType' object has no attribute 'get', unable to reach config generator pages

Steps:

1. Clone backend-apiPR18 and dashboardPR153
2. Manually build docker image with docker build -t hummingbot/backend-api:latest -f Dockerfile . and docker build -t hummingbot/dashboard:latest -f Dockerfile .
3. clone https://github.com/hummingbot/deploy
4. for setup.sh removed line "docker compose pull"
5. bash setup.sh
6. go to different config generator tabs

Actual:
There's AttributeError: 'NoneType' object has no attribute 'get', unable to reach config generator pages

image


```
2024-06-25 19:18:14.563 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/envs/dashboard/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/home/dashboard/frontend/pages/config/bollinger_v1/app.py", line 27, in <module>
    get_default_config_loader("bollinger_v1")
  File "/home/dashboard/frontend/components/config_loader.py", line 14, in get_default_config_loader
    config_controller_name = default_config.get("controller_name", controller_name)
AttributeError: 'NoneType' object has no attribute 'get'
```

image
image

**Review by nikspz — APPROVED** [review]

**Comment by rapcmia** [comment]
Do fresh install on both this PR153 and PR18
- Purge all previous installations and env 
- Clone both PR successfully and setup using source with hummingbot-broker 
- Successfully added account and add connectors ok 
- Successfully add connectors to `master_account` ok 
- Check portfolio again and loaded the balances however returning error 
  image
  ```
  # dashboard logs 
  2024-06-28 11:02:56.753 Uncaught app exception
  Traceback (most recent call last):
    File "/Users/rapcomia/miniconda3/envs/dashboard/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
      exec(code, module.__dict__)
    File "/Users/rapcomia/github/dashboard/153/frontend/pages/orchestration/portfolio/app.py", line 139, in <module>
      account_history_df['timestamp'] = pd.to_datetime(account_history_df['timestamp'])
    File "/Users/rapcomia/miniconda3/envs/dashboard/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
      indexer = self.columns.get_loc(key)
    File "/Users/rapcomia/miniconda3/envs/dashboard/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
      raise KeyError(key)
  KeyError: 'timestamp'
  2024-06-28 11:03:03.699 Uncaught app exception
  Traceback (most recent call last):
    File "/Users/rapcomia/miniconda3/envs/dashboard/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
      exec(code, module.__dict__)
    File "/Users/rapcomia/github/dashboard/153/frontend/pages/orchestration/portfolio/app.py", line 139, in <module>
      account_history_df['timestamp'] = pd.to_datetime(account_history_df['timestamp'])
    File "/Users/rapcomia/miniconda3/envs/dashboard/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
      indexer = self.columns.get_loc(key)
    File "/Users/rapcomia/miniconda3/envs/dashboard/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
      raise KeyError(key)
  KeyError: 'timestamp'
  ```
    - Removed added accounts and connectors
    - Add connector back to `master_account` only, still same result

Steps to reproduce:
1. Clone this PR and setup w/ backendPR18 + hummingbot-broker on source
2. Add connectors and go to `portfolio`
3. Page loads the connectors and balances but getting `KeyError: 'timestamp'` after

**Comment by rapcmia** [comment]
> * Check portfolio again and loaded the balances however returning error

This is now fixed on latest commit

**Pull request merged**
