### PR TITLE
Feat/database manager

### PR DESCRIPTION
**Pull request by cardosofede**
This PR is adding a database manager class to improve the communication with the sqlite database.
Also, the logic of the trade fees was included in the strategy data class and in the graphs.
Minor improvements in graph style too.

### CODE REVIEW

**Review by fengtality — APPROVED** [review]
Approved, but note that I couldn't get past this UX issue:

Screen Shot 2023-05-08 at 7 37 46 PM

Looks like I need to define a config file, but it's grayed out.

**Comment by cardosofede** [comment]
image
@fengtality is possible that you don't have trades available?

**Comment by fengtality** [comment]
Screen Shot 2023-05-09 at 10 13 14 AM

works well on `binance_paper_trade`

**Review by fengtality — APPROVED** [review]

**Review by nikspz — APPROVED** [review]
Tests performed:

- Cloned and install feature branch and PR6288
- conda env create -f environment_conda.yml
- conda activate streamlit-apps
- streamlit run main.py
- Copied URL to browser
- Created symlink with ln -s /path/to/hummingbot/data data
- Review Strategy Performance now shows fees in USDT for binance spot
- Confirmed fees amount is showing correct amount
Note: for binance perpetual there's ongoing issue with `AttributeError: module 'ccxt' has no attribute 'binance_perpetual'
`

**Comment by nikspz** [comment]
Mentioned that ccxt will be removed in another PR

**Pull request merged**
