### PR TITLE
Feat/bot orchestration v2

### PR DESCRIPTION
**Pull request by cardosofede**

### CODE REVIEW

**Comment by fengtality** [comment]
I got this error when creating a bot:
```
docker: Error response from daemon: create ./hummingbot_files/bot_configs/hummingbot-1/conf: "./hummingbot_files/bot_configs/hummingbot-1/conf" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```

**Comment by cardosofede** [comment]
@fengtality did you reinstall the conda environment? I upgraded the docker manager

**Comment by fengtality** [comment]
@cardosofede How is Docker Manager supposed to be installed? It's not in the conda environment file

**Comment by philipp1992** [comment]
also running into this issue, any fix?

**Pull request merged**
